name: Run Tests

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: trilom/file-changes-action@v1.2.3
    - name: Checks for new files
      run: |
         echo '${{ steps.file_changes.outputs.files_added}}'
    - name: Set Up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: test with green
      run: |
        green -vvv
